spring.application.name: ares-guard
spring.main.web-application-type: NONE
com:
  andreidodu:
    ares-guard:
      bot:
        google:
          query-url: https://developers.google.com/search/apis/ipranges/googlebot.json
        bing:
          query-url: https://www.bing.com/toolbox/bingbot.json